service: community-app
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: src/index.html

- url: /(.*)
  static_files: dist/\1
  upload: src/(.*)